name = "tsuduri-pwa"
compatibility_date = "2026-03-16"

# Pages Functions を使う前提
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "tsuduri-db"
database_id = "5a5dc7f2-7f70-443a-8f30-4baddef1e241"
migrations_dir = "migrations"